# Generated by Django 4.1.7 on 2023-06-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='url_orpath',
            new_name='url_or_path',
        ),
    ]
