# Generated by Django 4.2.2 on 2023-06-18 15:43

from django.db import migrations, models
import utils.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[utils.model_validator.validate_png]),
        ),
    ]
